import type { AppState } from './types'

export const seedState = (): AppState => ({
  users: [
    {
      id: 'u-taller',
      name: 'Carlos Mendoza',
      username: 'cmendoza',
      email: 'admin@taller.com',
      password: 'taller123',
      role: 'taller',
      phone: '555-100-2000',
      address: 'Av. Industria 301, Garage 301',
      avatar: '',
    },
    {
      id: 'u-cliente',
      name: 'Ana Ruiz',
      username: 'anaruiz',
      email: 'ana@correo.com',
      password: 'cliente123',
      role: 'cliente',
      phone: '555-310-4488',
      address: 'Calle Roble 14',
      avatar: '',
    },
    {
      id: 'u-cliente-2',
      name: 'Luis Herrera',
      username: 'lherrera',
      email: 'luis@correo.com',
      password: 'cliente123',
      role: 'cliente',
      phone: '555-220-1199',
      address: 'Insurgentes 890',
      avatar: '',
    },
  ],
  vehicles: [
    {
      id: 'v1',
      plate: 'ABC-1234',
      brand: 'Nissan',
      model: 'Sentra',
      year: 2020,
      color: 'Plata',
      vin: '3N1AB8CV5LY123456',
      ownerId: 'u-cliente',
      mileage: 64210,
      status: 'en_taller',
      photo: '',
    },
    {
      id: 'v2',
      plate: 'XYZ-7788',
      brand: 'Volkswagen',
      model: 'Jetta',
      year: 2018,
      color: 'Negro',
      vin: '3VW2B7AJ8JM654321',
      ownerId: 'u-cliente',
      mileage: 98140,
      status: 'activo',
      photo: '',
    },
    {
      id: 'v3',
      plate: 'HND-4410',
      brand: 'Honda',
      model: 'Civic',
      year: 2022,
      color: 'Rojo',
      vin: '19XFC2F59NE987654',
      ownerId: 'u-cliente-2',
      mileage: 21500,
      status: 'en_taller',
      photo: '',
    },
  ],
  appointments: [
    {
      id: 'a1',
      clientId: 'u-cliente',
      vehicleId: 'v1',
      date: new Date().toISOString().slice(0, 10),
      time: '09:30',
      service: 'Frenos',
      status: 'confirmada',
      notes: 'Chirrido al frenar en frío',
    },
    {
      id: 'a2',
      clientId: 'u-cliente-2',
      vehicleId: 'v3',
      date: new Date().toISOString().slice(0, 10),
      time: '11:00',
      service: 'Afinación mayor',
      status: 'en_proceso',
      notes: 'Mantenimiento de 20,000 km',
    },
    {
      id: 'a3',
      clientId: 'u-cliente',
      vehicleId: 'v2',
      date: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
      time: '16:00',
      service: 'Cambio de aceite',
      status: 'pendiente',
      notes: '',
    },
  ],
  orders: [
    {
      id: 'o1',
      folio: 'OT-1042',
      vehicleId: 'v1',
      clientId: 'u-cliente',
      mechanic: 'Miguel Torres',
      description: 'Cambio de balatas delanteras y rectificado de discos',
      status: 'en_proceso',
      createdAt: new Date().toISOString(),
      labor: 850,
      discount: 0,
      materials: [],
      parts: [
        { partId: 'p1', qty: 1 },
        { partId: 'p2', qty: 2 },
      ],
    },
    {
      id: 'o2',
      folio: 'OT-1043',
      vehicleId: 'v3',
      clientId: 'u-cliente-2',
      mechanic: 'Sofía Díaz',
      description: 'Afinación mayor + diagnóstico de sensores',
      status: 'entregada',
      createdAt: new Date().toISOString(),
      labor: 1200,
      discount: 0,
      materials: [],
      parts: [{ partId: 'p4', qty: 1 }],
    },
  ],
  parts: [
    { id: 'p1', sku: 'FRN-001', name: 'Kit balatas delanteras Sentra', category: 'Frenos', stock: 6, minStock: 3, price: 1280, cost: 780 },
    { id: 'p2', sku: 'FRN-014', name: 'Disco de freno 280 mm', category: 'Frenos', stock: 4, minStock: 2, price: 890, cost: 520 },
    { id: 'p3', sku: 'ACE-010', name: 'Aceite sintético 5W-30 4L', category: 'Lubricantes', stock: 18, minStock: 8, price: 620, cost: 380 },
    { id: 'p4', sku: 'FIL-022', name: 'Filtro de aire Civic', category: 'Filtros', stock: 1, minStock: 3, price: 340, cost: 180 },
    { id: 'p5', sku: 'SUS-008', name: 'Amortiguador delantero Jetta', category: 'Suspensión', stock: 2, minStock: 2, price: 2150, cost: 1320 },
    { id: 'p6', sku: 'ELE-031', name: 'Batería 12V 600 CCA', category: 'Eléctrico', stock: 5, minStock: 2, price: 1890, cost: 1100 },
  ],
  partRequests: [
    {
      id: 'r1',
      clientId: 'u-cliente',
      vehicleId: 'v1',
      partId: 'p1',
      qty: 1,
      status: 'apartada',
      createdAt: new Date().toISOString(),
    },
  ],
  observations: [
    {
      id: 'ob1',
      vehicleId: 'v1',
      authorId: 'u-taller',
      text: 'Discos rayados. Se recomienda rectificado y no solo cambio de balatas.',
      photos: [],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'ob2',
      vehicleId: 'v1',
      authorId: 'u-cliente',
      text: 'El ruido se nota más al bajar pendientes. Favor de revisar el líquido de frenos.',
      photos: [],
      createdAt: new Date(Date.now() - 1800000).toISOString(),
    },
  ],
  coupons: [],
})
